- name: Install git on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - wget
        - curl
        - ca-certificates
        - software-properties-common
        
    - name: Install git
      apt:
        name: git
        state: present

- name: Install Google Chrome on Ubuntu
  hosts: localhost        # Run the playbook on the local machine
  become: yes             # Sudo privileges for package installation
  tasks:
    - name: Add Google Chrome repository
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present

    - name: Install Google Chrome
      apt:
        name: google-chrome-stable
        state: present

- name: Install VScode
  hosts: localhost
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - wget
        - curl
        - gnupg
        - ca-certificates

    - name: Add Microsoft GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add Visual Studio Code repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present

    - name: Install Visual Studio Code
      apt:
        name: code
        state: present

- name: Install neovim on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - software-properties-common

    - name: Add neovim repository
      apt_repository:
        repo: ppa:neovim-ppa/stable
        state: present

    - name: Install neovim
      apt:
        name: neovim
        state: present
  
- name: Install btop on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Install btop
      command: snap install btop

- name: Install autojump on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Install autojump
      apt:
        name: autojump
        state: present
      
- name: Add script autojump to ~/.bashrc
  hosts: localhost
  become: yes
  tasks:
    - name: Add script autojump to ~/.bashrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: '[[ -s /usr/share/autojump/autojump.bash ]] && source /usr/share/autojump/autojump.bash'
        state: present
        insertafter: EOF
